### ISSUE TITLE
Bug: Replace beeps with spoken indicators

### ISSUE THREAD

**Issue by yplassiard** [josephsl/screenCurtain#2]
### Actual behavior

When toggling screen curtain on or off, a beep is eared by the user indicating the screen dimming state.

### Expected behavior
As it is done within NVDA itself for all toggling features (echo by character or word, review cursor tethering, etc.) it would be better to have some spoken messages indicating something like:
- "screen dimmed": when the screen becomes dimmed, i.e. black
- "screen restored": when the screen visibility has been restored to its default state.

**Comment by josephsl** [comment]
Hi, this will require careful design so this notification can be heard after all speech sequences are done (likely using a queue). Thanks.

**Comment by josephsl** [comment]
Hi,

Note: do not use queueHandler.queueFunction as status message is lost in the sea of focus messages. Thus using wx.CallLater with the toggle message spoken a second after screen curtain is toggled. Startup tone will still be heard.

Thanks.
